# Generated by Django 4.2.5 on 2023-09-19 06:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0002_remove_menu_one_type_per_user_alter_menu_active"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="meal",
            constraint=models.UniqueConstraint(
                fields=("menu", "week", "day"), name="unique_menu_week_day"
            ),
        ),
    ]
