[tool.bandit]
skips = ["B101"]

[tool.black]
line-length = 119

[tool.isort]
profile = "black"
src_paths = ["core"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.testing_settings"
python_files = "test_*.py"
addopts = "--nomigrations --disable-socket"

[tool.ruff]
line-length=119

[tool.ruff.per-file-ignores]
"*/migrations/*.py"= ['E501']
