[tool.bandit]
skips = ["B101"]

[tool.black]
line-length = 119

[tool.coverage.report]
fail_under = 100
omit = [
    "*/migrations/*",
]
show_missing = true
skip_covered = true

[tool.isort]
profile = "black"
src_paths = ["core"]

[tool.pytest.ini_options]
addopts = "--nomigrations --disable-socket"
DJANGO_SETTINGS_MODULE = "core.testing_settings"
filterwarnings = [
    # Enable warnings as errors.
    "error",
]

[tool.ruff]
line-length=119
