[tool.bandit]
skips = ["B101"]

[tool.black]
line-length = 119

[tool.coverage.report]
fail_under = 100
omit = [
    "*/migrations/*",
]
show_missing = true
skip_covered = true

[tool.isort]
profile = "black"
src_paths = ["core"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "core.testing_settings"
python_files = "test_*.py"
addopts = "--nomigrations --disable-socket"
filterwarnings = [
    "error",
    "ignore:The --rsyncdir command line argument and rsyncdirs config variable are deprecated.:DeprecationWarning",
]
testpaths = [
    "accounts",
    "meals",
]

[tool.ruff]
line-length=119

[tool.ruff.per-file-ignores]
"*/migrations/*.py"= ['E501']
